# Generated by Django 5.2.5 on 2025-08-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_n',
            field=models.DateField(blank=True, null=True),
        ),
    ]
