# Generated by Django 5.2.5 on 2025-08-21 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos_api', '0002_initial'),
        ('usuarios_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cargos_api.cargo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estudioF',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios_api.estudioformal'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios_api.genero'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios_api.tipodocumento'),
        ),
    ]
