# Generated by Django 5.2.5 on 2025-08-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_api', '0002_alter_usuario_fecha_n'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='software',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
