# Generated by Django 5.1.4 on 2025-09-21 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_api', '0002_autorizacion_permiso_permisosusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_n',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='resolucion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
