# Generated by Django 5.2.5 on 2025-08-28 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
        ('usuarios_api', '0003_alter_usuario_software'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='dependencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.dependencia'),
        ),
    ]
