# Generated by Django 5.1.4 on 2025-09-21 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_api', '0003_alter_usuario_fecha_n_alter_usuario_resolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='estudioF',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios_api.estudioformal'),
        ),
    ]
