# Generated by Django 5.2.5 on 2025-08-28 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos_api', '0003_remove_cargo_codigocargo'),
        ('general', '0001_initial'),
        ('usuarios_api', '0005_alter_usuario_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargos_api.cargo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.dependencia'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios_api.estado'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estudioF',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios_api.estudioformal'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_n',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios_api.genero'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='resolucion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios_api.rol'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='software',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios_api.tipodocumento'),
        ),
    ]
