# Generated by Django 5.2.5 on 2025-08-29 11:20

import core_apps.usuarios_api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cargos_api', '0004_alter_cargo_fechacreacion'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('general', '0001_initial'),
        ('usuarios_api', '0006_alter_usuario_cargo_alter_usuario_dependencia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bitacora',
            options={'ordering': ['-fecha']},
        ),
        migrations.RenameField(
            model_name='solicitud',
            old_name='fechaAprovada',
            new_name='fechaAprobada',
        ),
        migrations.AddField(
            model_name='bitacora',
            name='cambios',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='object_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='accion',
            field=models.CharField(choices=[('CREAR', 'Crear'), ('ACTUALIZAR', 'Actualizar'), ('ELIMINAR', 'Eliminar'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión')], max_length=20),
        ),
        migrations.AlterField(
            model_name='estado',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='estadosolicitud',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='estudioformal',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='formacioncomplementaria',
            name='certificado',
            field=models.FileField(upload_to=core_apps.usuarios_api.models.certificado_upload_to),
        ),
        migrations.AlterField(
            model_name='formacioncomplementaria',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios_api.tipocertificado'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='genero',
            name='sigla',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios_api.estadosolicitud'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios_api.tiposolicitud'),
        ),
        migrations.AlterField(
            model_name='tipocertificado',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='sigla',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='tiposolicitud',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cargos_api.cargo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.dependencia'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios_api.estado'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estudioF',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios_api.estudioformal'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios_api.genero'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='num_doc',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios_api.rol'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='software',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sin acceso'), (1, 'Acceso básico'), (2, 'Acceso avanzado')], default=1),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios_api.tipodocumento'),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.UniqueConstraint(fields=('tipo_doc', 'num_doc'), name='uniq_tipo_doc_num_doc'),
        ),
    ]
