# Generated by Django 5.1.6 on 2025-09-09 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_api', '0007_alter_bitacora_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Autorización',
                'verbose_name_plural': 'Autorizaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(help_text='Identificador único interno (ejemplo: funcionario_agregar, cargo_editar)', max_length=150, unique=True)),
                ('autorizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='usuarios_api.autorizacion')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'ordering': ['autorizacion', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PermisosRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios_api.permiso', verbose_name='Autorizaciones')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios_api.rol', verbose_name='Rol')),
            ],
            options={
                'unique_together': {('rol', 'permiso')},
            },
        ),
    ]
