# Generated by Django 5.2.5 on 2025-09-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_api', '0007_alter_bitacora_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
