# Generated by Django 5.2.5 on 2025-09-03 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos_api', '0016_cargousuario_observacion_and_more'),
        ('usuarios_api', '0008_bitacora_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cargos_api.cargo'),
        ),
    ]
