# Generated by Django 5.1.6 on 2025-09-11 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_api', '0008_autorizacion_permiso_permisosrol'),
        ('usuarios_api', '0009_alter_usuario_cargo'),
    ]

    operations = [
    ]
