# Generated by Django 5.1.6 on 2025-09-11 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_api', '0010_merge_20250911_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisosUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otorgado_en', models.DateTimeField(auto_now_add=True)),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios_api.permiso', verbose_name='Autorizaciones')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'unique_together': {('usuario', 'permiso')},
            },
        ),
        migrations.DeleteModel(
            name='PermisosRol',
        ),
    ]
