# Generated by Django 5.2.5 on 2025-08-21 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoNombre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoCargo', models.CharField(max_length=10, unique=True)),
                ('idp', models.CharField(max_length=10)),
                ('resolucion', models.CharField(max_length=200)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.area')),
                ('cargo_nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargos_api.cargonombre')),
            ],
        ),
        migrations.CreateModel(
            name='CargoFuncion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion', models.TextField()),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargos_api.cargo')),
            ],
        ),
        migrations.CreateModel(
            name='CargoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAsignacion', models.DateTimeField(auto_now_add=True)),
                ('fechaFin', models.DateTimeField(auto_now=True)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grado', models.CharField(max_length=100)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargos_api.cargo')),
            ],
        ),
    ]
