# Generated by Django 5.1.4 on 2025-09-13 05:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoNombre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoVinculacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Idp',
            fields=[
                ('idp_id', models.CharField(default='0', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('fechaCreacion', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='IdpxCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolucion', models.CharField(max_length=200)),
                ('resolucion_archivo', models.FileField(blank=True, null=True, upload_to='resolucionesCargo/')),
                ('fechaCreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fechaActualizacion', models.DateTimeField(auto_now=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.centro')),
                ('cargoNombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargos_api.cargonombre')),
            ],
        ),
        migrations.CreateModel(
            name='CargoFuncion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion', models.TextField()),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargos_api.cargo')),
            ],
        ),
        migrations.CreateModel(
            name='CargoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField(auto_now_add=True)),
                ('fechaRetiro', models.DateField(blank=True, null=True)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grado', models.CharField(max_length=100)),
                ('resolucion', models.CharField(max_length=100)),
                ('resolucion_archivo', models.FileField(blank=True, null=True, upload_to='resolucionesCargoUsuario/')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargos_api.cargo')),
            ],
        ),
    ]
