# Generated by Django 5.1.4 on 2025-09-13 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargos_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cargousuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cargo',
            name='estadoCargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargos_api.estadocargo'),
        ),
        migrations.AddField(
            model_name='cargousuario',
            name='estadoVinculacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargos_api.estadovinculacion'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='idp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargos_api.idp'),
        ),
        migrations.AddField(
            model_name='idpxcargo',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_idps', to='cargos_api.cargo'),
        ),
        migrations.AddField(
            model_name='idpxcargo',
            name='idp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial_cargos', to='cargos_api.idp'),
        ),
    ]
