# Generated by Django 5.2.5 on 2025-08-28 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargos_api', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='codigoCargo',
        ),
    ]
