# Generated by Django 5.1.6 on 2025-09-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos_api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idp',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
