# Generated by Django 5.2.5 on 2025-08-29 11:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos_api', '0003_remove_cargo_codigocargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='fechaCreacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
