# Generated by Django 5.1.6 on 2025-09-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos_api', '0004_alter_cargo_centro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='fechaActualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
