# Generated by Django 5.2.5 on 2025-08-30 23:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos_api', '0004_alter_cargo_fechacreacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='fechaCreacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
