# Generated by Django 5.2.5 on 2025-08-31 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos_api', '0005_alter_cargo_fechacreacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='cargousuario',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cargos_api.estadocargo'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='idp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargos_api.idp'),
        ),
    ]
