# Generated by Django 5.1.4 on 2025-09-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos_api', '0005_alter_cargo_fechaactualizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargousuario',
            name='grado',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cargousuario',
            name='resolucion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cargousuario',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
