# Generated by Django 5.2.5 on 2025-08-31 18:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos_api', '0006_idp_cargousuario_estado_alter_cargo_idp'),
    ]

    operations = [
        migrations.AddField(
            model_name='idp',
            name='fechaCreacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cargousuario',
            name='fechaRetiro',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
