# Generated by Django 5.1.4 on 2025-09-22 16:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos_api', '0006_alter_cargousuario_grado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='fechaCreacion',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='idp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cargos_api.idp'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='resolucion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
