# Generated by Django 5.1.4 on 2025-09-22 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos_api', '0007_alter_cargo_fechacreacion_alter_cargo_idp_and_more'),
        ('general', '0002_alter_red_centro'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='regional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general.regional'),
        ),
    ]
