# Generated by Django 5.2.5 on 2025-08-31 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos_api', '0007_idp_fechacreacion_alter_cargousuario_fecharetiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargousuario',
            name='fechaInicio',
            field=models.DateField(auto_now_add=True),
        ),
    ]
