# Generated by Django 5.2.5 on 2025-09-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos_api', '0008_alter_cargousuario_fechainicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='resolucion_archivo',
            field=models.FileField(blank=True, null=True, upload_to='resoluciones/'),
        ),
    ]
