# Generated by Django 5.2.5 on 2025-09-01 07:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos_api', '0009_cargo_resolucion_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='fechaCreacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
