# Generated by Django 5.2.5 on 2025-09-02 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos_api', '0010_alter_cargo_fechacreacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoVinculacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cargousuario',
            name='estado',
        ),
        migrations.AddField(
            model_name='cargousuario',
            name='estadoVinculacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cargos_api.estadovinculacion'),
        ),
    ]
