# Generated by Django 5.2.5 on 2025-09-02 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos_api', '0011_estadovinculacion_remove_cargousuario_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargousuario',
            name='resolucion_archivo',
            field=models.FileField(blank=True, null=True, upload_to='resolucionesCargoUsuario/'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='resolucion_archivo',
            field=models.FileField(blank=True, null=True, upload_to='resolucionesCargo/'),
        ),
        migrations.AlterField(
            model_name='cargousuario',
            name='estadoVinculacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargos_api.estadovinculacion'),
        ),
    ]
