# Generated by Django 5.2.5 on 2025-09-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos_api', '0012_cargousuario_resolucion_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargousuario',
            name='fechaRetiro',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
