# Generated by Django 5.2.5 on 2025-09-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos_api', '0013_alter_cargousuario_fecharetiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargousuario',
            name='fechaRetiro',
            field=models.DateField(blank=True, null=True),
        ),
    ]
