# Generated by Django 5.2.5 on 2025-09-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos_api', '0014_alter_cargousuario_fecharetiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargonombre',
            name='funcion',
            field=models.TextField(default='Sin función registrada'),
        ),
        migrations.DeleteModel(
            name='CargoFuncion',
        ),
    ]
