# Generated by Django 5.1.4 on 2025-09-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos_api', '0014_alter_cargousuario_fecharetiro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idp',
            name='id',
        ),
        migrations.RemoveField(
            model_name='idp',
            name='numero',
        ),
        migrations.AddField(
            model_name='idp',
            name='idp_id',
            field=models.CharField(default='null', max_length=10, primary_key=True, serialize=False),
        ),
    ]
