# Generated by Django 5.1.4 on 2025-09-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos_api', '0015_remove_idp_id_remove_idp_numero_idp_idp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idp',
            name='idp_id',
        ),
        migrations.AddField(
            model_name='idp',
            name='numero',
            field=models.CharField(default='0', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
