# Generated by Django 5.2.5 on 2025-09-02 16:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos_api', '0015_cargonombre_funcion_delete_cargofuncion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargousuario',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cargousuario',
            name='fechaInicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
