# Generated by Django 5.2.5 on 2025-09-07 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos_api', '0016_cargousuario_observacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelacionCascada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_hijo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos_superiores', to='cargos_api.cargo')),
                ('cargo_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos_dependientes', to='cargos_api.cargo')),
            ],
        ),
    ]
