# Generated by Django 5.1.4 on 2025-09-04 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargos_api', '0016_remove_idp_idp_id_idp_numero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idp',
            old_name='numero',
            new_name='idp_id',
        ),
    ]
