# Generated by Django 5.1.6 on 2025-09-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos_api', '0017_rename_numero_idp_idp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='idp',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
