# Generated by Django 5.2.5 on 2025-09-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos_api', '0017_relacioncascada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargousuario',
            name='fechaRetiro',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
