# Generated by Django 5.1.6 on 2025-09-11 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargos_api', '0018_alter_cargousuario_fecharetiro'),
        ('cargos_api', '0018_idp_estado'),
    ]

    operations = [
    ]
