# Generated by Django 5.1.6 on 2025-09-11 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos_api', '0018_idp_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdpxCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargos_api.cargo', verbose_name='Cargo en idp')),
                ('idp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargos_api.idp', verbose_name='Idp en cargo')),
            ],
            options={
                'unique_together': {('idp_id', 'cargo')},
            },
        ),
    ]
