# Generated by Django 5.1.6 on 2025-09-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos_api', '0020_idpxcargo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='idpxcargo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='idpxcargo',
            name='fecha_asignacion',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='idpxcargo',
            name='fecha_desasignación',
            field=models.DateField(blank=True, null=True),
        ),
    ]
