# Generated by Django 5.1.6 on 2025-09-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos_api', '0021_alter_idpxcargo_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idpxcargo',
            name='fecha_desasignación',
            field=models.DateField(blank=True, null=True),
        ),
    ]
