# Generated by Django 5.1.6 on 2025-09-11 15:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos_api', '0022_alter_idpxcargo_fecha_desasignación'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idpxcargo',
            name='fecha_asignacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='idpxcargo',
            name='fecha_desasignación',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
