# Generated by Django 5.1.6 on 2025-09-11 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargos_api', '0023_alter_idpxcargo_fecha_asignacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idpxcargo',
            old_name='cargo',
            new_name='cargo_id',
        ),
    ]
