# Generated by Django 5.1.6 on 2025-09-11 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargos_api', '0024_rename_cargo_idpxcargo_cargo_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idpxcargo',
            old_name='cargo_id',
            new_name='cargo',
        ),
        migrations.RenameField(
            model_name='idpxcargo',
            old_name='idp_id',
            new_name='idp',
        ),
    ]
