# Generated by Django 5.1.6 on 2025-08-20 15:57

import ckeditor.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('funcionarios', '0001_test_migracion'),
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacoras',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accion', ckeditor.fields.RichTextField(max_length=50, verbose_name='bitacora')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuarios', verbose_name='autor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Red',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=250)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.centros')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=250)),
                ('red', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='funcionarios.red')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
