# Generated by Django 5.1.6 on 2025-08-20 15:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargos', '0002_initial'),
        ('formacion', '0002_initial'),
        ('users', '0001_test_migracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=250)),
                ('sigla', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TiposDoc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('TI', 'Tarjeta de identidad'), ('RC', 'Registro civil')], max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=250)),
                ('apellido', models.CharField(max_length=255)),
                ('num_doc', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('fecha_ingreso', models.DateField(auto_now=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cargos.cargos')),
                ('estudio_formal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='formacion.estudioformal')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.generos')),
                ('tipo_doc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.tiposdoc')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
