# Generated by Django 5.2.4 on 2025-09-22 14:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
        ('grupoSena_api', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NombreGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Grupo')),
            ],
        ),
        migrations.RemoveField(
            model_name='gruposena',
            name='centro',
        ),
        migrations.RemoveField(
            model_name='gruposena',
            name='estadoGrupo',
        ),
        migrations.RemoveField(
            model_name='gruposena',
            name='fechaActualizacion',
        ),
        migrations.RemoveField(
            model_name='gruposena',
            name='fechaCreacion',
        ),
        migrations.RemoveField(
            model_name='gruposena',
            name='resolucion',
        ),
        migrations.AddField(
            model_name='gruposena',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='general.area', verbose_name='Área Funcional'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gruposena',
            name='capacidad',
            field=models.PositiveIntegerField(default=10, verbose_name='Capacidad Máxima'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gruposena',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grupoSena_api.estadogrupo', verbose_name='Estado del Grupo'),
        ),
        migrations.AddField(
            model_name='gruposena',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gruposena',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización'),
        ),
        migrations.AddField(
            model_name='gruposena',
            name='observacion',
            field=models.TextField(blank=True, null=True, verbose_name='Observación'),
        ),
        migrations.AddField(
            model_name='gruposena',
            name='resolucion1',
            field=models.FileField(blank=True, null=True, upload_to='resoluciones/', verbose_name='Resolución 1'),
        ),
        migrations.AddField(
            model_name='gruposena',
            name='resolucion2',
            field=models.FileField(blank=True, null=True, upload_to='resoluciones/', verbose_name='Resolución 2'),
        ),
        migrations.AddField(
            model_name='usuariogrupo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuariogrupo',
            name='fecha_ingreso',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariogrupo',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estadogrupo',
            name='estado',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='gruposena',
            name='lider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_lider', to=settings.AUTH_USER_MODEL, verbose_name='Líder'),
        ),
        migrations.AlterUniqueTogether(
            name='usuariogrupo',
            unique_together={('usuario', 'grupo')},
        ),
        migrations.AlterField(
            model_name='gruposena',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grupoSena_api.nombregrupo', verbose_name='Nombre del Grupo'),
        ),
    ]
