# Generated by Django 5.2.4 on 2025-09-22 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupoSena_api', '0003_nombregrupo_remove_gruposena_centro_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gruposena',
            name='lider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_dirigidos', to=settings.AUTH_USER_MODEL, verbose_name='Líder del Grupo'),
        ),
        migrations.AlterField(
            model_name='gruposena',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre del Grupo'),
        ),
    ]
