# Generated by Django 5.2.4 on 2025-09-22 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupoSena_api', '0004_alter_gruposena_lider_alter_gruposena_nombre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NombreGrupo',
        ),
    ]
