# Generated by Django 5.2.4 on 2025-09-23 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupoSena_api', '0005_delete_nombregrupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NombreGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Grupo')),
            ],
        ),
        migrations.RemoveField(
            model_name='gruposena',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='gruposena',
            name='resolucion1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre de Resolución'),
        ),
        migrations.AddField(
            model_name='gruposena',
            name='nombre_grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='grupoSena_api.nombregrupo', verbose_name='Nombre del Grupo'),
        ),
    ]
