# Generated by Django 5.2.4 on 2025-09-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupoSena_api', '0006_nombregrupo_remove_gruposena_nombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gruposena',
            old_name='nombre_grupo',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='gruposena',
            name='fecha_fin',
        ),
        migrations.AlterField(
            model_name='gruposena',
            name='fecha_creacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Creación'),
        ),
    ]
