# Generated by Django 5.2.4 on 2025-09-24 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupoSena_api', '0007_rename_nombre_grupo_gruposena_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gruposena',
            name='nombre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='grupoSena_api.nombregrupo', verbose_name='Nombre del Grupo'),
            preserve_default=False,
        ),
    ]
