# Generated by Django 5.2.4 on 2025-09-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupoSena_api', '0008_alter_gruposena_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gruposena',
            name='resolucion2',
            field=models.FileField(blank=True, null=True, upload_to='resolucionesGrupoUsuario/', verbose_name='Resolución 2'),
        ),
    ]
