# Generated by Django 5.2.4 on 2025-09-25 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupoSena_api', '0009_alter_gruposena_resolucion2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gruposena',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default='2025-09-24', verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
    ]
