# Generated by Django 5.2.4 on 2025-09-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupoSena_api', '0010_alter_gruposena_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='gruposena',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Cierre'),
        ),
    ]
