# Generated by Django 5.1.4 on 2025-09-13 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoCentro', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoDependencia', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Regional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoRegional', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Red',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoRed', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.centro')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoArea', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('red', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.red')),
            ],
        ),
        migrations.AddField(
            model_name='centro',
            name='regional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.regional'),
        ),
    ]
